### ISSUE TITLE
Add "Dimensions" Editor to admin pages.

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#11]
Duplicate the functionality of "Trusted AI Resources" for a new "Dimensions" editor. 

Copy Components/AdminProviders.js to Components/Dimensions.js and modify to update the Dimensions collection.

Make sure to include the "Dimension ID" field in the update form, because that is the key that is used by the subdimensions to link to the parent dimension.

**Comment by aaronlugo** [comment]
This is what we did this morning right?

**Comment by geverit4** [comment]
Yes - this is what we started this morning.  It's not done yet.

**Comment by aaronlugo** [comment]
done

**Comment by geverit4** [comment]
Looks great!
