### ISSUE TITLE
Modal editor not displaying properly.

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#17]
The dimensions for the controls on the Edit Question modal are not right.  Data is hidden and cut off in the display, even though it is in the database. 

The dropdowns at the top and the Score fields are too small.  

Please apply styling to show all of the data.

![Screen Shot 2022-03-21 at 4 47 55 PM](https://user-images.githubusercontent.com/1187616/159361582-78314aea-8aad-477b-b916-e2f652f72c27.png)

**Comment by aaronlugo** [comment]
Is this only UI stuff? is there a problem with the displayed data?

**Comment by geverit4** [comment]
I updated a few of the column breaks so that they display better on portrait page width displays.

There are still some edge cases that we can clean up, like the display for slider min/max/default

![Screen Shot 2022-03-22 at 8 24 30 AM](https://user-images.githubusercontent.com/1187616/159481420-3ffa3d8a-5d55-40e8-95b6-34b1eb7e4f5d.png)
