### ISSUE TITLE
Only first Dimension saves to DB

### ISSUE THREAD

**Issue by teveritt** [appliedrelevance/design-assistant#18]
Go to Dimensions
Edit an entry
Save
Try to edit another entry
An error in the console is displayed and you can't save your changes
![Screenshot 2022-03-21 173703](https://user-images.githubusercontent.com/65302023/159369215-85d608f2-52e6-49a3-8a5e-7b57ddf6a4a0.png)

**Comment by aaronlugo** [comment]
Cannot reproduce it @teveritt  Can you share more details about the error?
