### ISSUE TITLE
Edit a Subdimension displays the wrong entry

### ISSUE THREAD

**Issue by teveritt** [appliedrelevance/design-assistant#19]
Go to the Subdimensions page
Select a specific entry to edit.
The entry that opens isn't the entry you selected.
![Screenshot 2022-03-21 173703](https://user-images.githubusercontent.com/65302023/159371773-1b39170d-7b56-4669-8dac-4664625d67fb.png)
![Screenshot 2022-03-21 180147](https://user-images.githubusercontent.com/65302023/159371776-8fd71c0e-3d98-4bea-9f51-b51fe146f3a4.png)

**Comment by aaronlugo** [comment]
Done
