### ISSUE TITLE
Need placeholder for Strengths and Opportunities fields

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#20]
If you somehow remove the content of the strength or opportunity field, the field disappears and there is nowhere to click.   Can we use placeholders?  If not, we need to synthesize them so that there is something to click on.
![Screen Shot 2022-03-22 at 8 20 50 AM](https://user-images.githubusercontent.com/1187616/159480978-f38003a7-d17e-4dae-8c9b-658bc8a47a67.png)

**Comment by aaronlugo** [comment]
what if we put: "No recommendations yet" if there is empty value? @geverit4

**Comment by aaronlugo** [comment]
Done
