### ISSUE TITLE
Create a .docx generator for assessment reports.

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#23]
https://docx.js.org/#/

Use the docx.js package to generate a Word document that looks like the useCase PDF attached.  

It should mirror the contents of the report as much as possible, starting with the current Certification report.  
 

[Responsible AI Certification Feb 2022.pdf](https://github.com/appliedrelevance/design-assistant/files/8343499/Responsible.AI.Certification.Feb.2022.pdf)
[use case report.pdf](https://github.com/appliedrelevance/design-assistant/files/8343500/use.case.report.pdf)
[org maturity report.pdf](https://github.com/appliedrelevance/design-assistant/files/8343503/org.maturity.report.pdf)
![Screen Shot 2022-03-24 at 12 24 50 PM](https://user-images.githubusercontent.com/1187616/159963573-fbb3635f-e34c-444f-a2a5-64a792a609be.png)

**Comment by geverit4** [comment]
Here is a link to an RAI Use Case Template to use as a starter.

**Comment by aaronlugo** [comment]
Can you test this @teveritt

**Comment by teveritt** [comment]
Word Documents generate successfully:
[Certification.docx](https://github.com/appliedrelevance/design-assistant/files/8597632/Certification.docx)
