### ISSUE TITLE
Compute actual subdimensions scores

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#31]
Create a score function for dimensions and subdimensions.

It should be a normalized weighted average for all of the scores for the question results values under that subdimension. 

Here's some pseudocode for what we want to do:

```
For each Dimension
   For each Subdimension in Dimension
      For each Answer in Subdimension
        Compute the normalized score for the answer: 
           AnswerScore  = ((AnswerValue-ScoreMin)/(ScoreMax - ScoreMin))*Weight  
           AnswerCount++
        SubDimSum += AnswerScore
     SubDimScore = SubDimSum/AnswerCount * SubDimWeight
  DimScore = DimSum/SubDimCount * DimWeight
```

Currently, the subdimension scores are random numbers.  They need to map to the scoring algorithm suggested by https://docs.google.com/spreadsheets/d/1SyXvZ--XPkWXZIDludAinN8mFE295hebOZnxJJOpTew/edit#gid=0

**Comment by aaronlugo** [comment]
What is  DimSum and DimCount and what value should I use if there is no weight ?

**Comment by geverit4** [comment]
Weighting has been removed from the scoring.  Here is the new spreadsheet with the scoring computations embedded in it: https://docs.google.com/spreadsheets/d/1wOAu4OnhNeehUx0dZ6Fp3t6vKX5VjzS2e70BI0OwbQc/edit#gid=0

**Comment by geverit4** [comment]
The computations are much simpler now.   We don't even need to compute anything except sum of answers and sum of points.
