### ISSUE TITLE
Project Names do not show up in landing page.

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#32]
The landing page shows "Unnamed Project (623d1c44c00057001698f358)" instead of the actual project name, even when it exists.  
This is at the bottom of the landing page after logging in. 

![Screen Shot 2022-03-29 at 9 59 00 AM](https://user-images.githubusercontent.com/1187616/160628747-b4c43463-6239-42fe-8aaa-d03e4505d96b.png)

**Comment by aaronlugo** [comment]
That happends with the submissions created before the fix

**Comment by geverit4** [comment]
Assigned to @teveritt  for testing.

**Comment by teveritt** [comment]
I just created two new projects and they're showing as Unnamed.
![Screenshot 2022-04-15 133003](https://user-images.githubusercontent.com/65302023/163602976-0e8bf2a0-8066-40cb-a595-99dc844f0487.png)

**Comment by aaronlugo** [comment]
<img width="1440" alt="Captura de Pantalla 2022-04-16 a la(s) 10 29 22" src="https://user-images.githubusercontent.com/24878290/163680920-0574d6d6-aeea-4b2b-b6fd-2a4343395ef3.png">
I cannot reproduce that 
@geverit4 @teveritt  See attachment, is working good for me

**Comment by teveritt** [comment]
Is this the same database as the live version?

**Comment by aaronlugo** [comment]
No,  but that should not be a problem since the page is using the same code to save and read the data

**Comment by geverit4** [comment]
I am having the same problem on the cloud version:

![Screen Shot 2022-04-19 at 7 54 16 AM](https://user-images.githubusercontent.com/1187616/163998020-e301f6b9-88d1-4f07-b411-97c2e4c3b784.png)

We need to investigate why the cloud version does not work and local dev versions do.
