### ISSUE TITLE
Add Weights to Dimension and Subdimension model and interface

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#33]
Subdimensions and Dimensions need to have weights associated with them for computing scoring.  

The weight should accept a floating point number and default to 0.5.   Put the weight after the description for both dimensions and subdimensions.

![Screen Shot 2022-04-14 at 5 30 51 PM](https://user-images.githubusercontent.com/1187616/163480476-e9110883-7530-493a-b403-dec974aa8d89.png)

https://docs.google.com/spreadsheets/d/1wOAu4OnhNeehUx0dZ6Fp3t6vKX5VjzS2e70BI0OwbQc/edit#gid=1593683221

**Comment by aaronlugo** [comment]
Done
