### ISSUE TITLE
Unable to add a new Dimension

### ISSUE THREAD

**Issue by teveritt** [appliedrelevance/design-assistant#37]
Nothing happens after clicking "Save" button.
![Screenshot 2022-04-18 132720](https://user-images.githubusercontent.com/65302023/163848287-c5c0d377-2b70-4626-8d3e-f49c29aa4885.png)
![Screenshot 2022-04-18 132959](https://user-images.githubusercontent.com/65302023/163848289-ceedde21-473a-4850-a099-c2f914d526cc.png)

**Comment by aaronlugo** [comment]
Done

**Comment by geverit4** [comment]
Doesn't work for me. 
![Screen Shot 2022-04-26 at 8 48 47 AM](https://user-images.githubusercontent.com/1187616/165303451-02ba7f63-4c05-414b-ad62-4d826edd613c.png)

**Comment by geverit4** [comment]
This does work.  However, the "Dimension ID" needs to be a number, and there should be better checking surrounding this.  Will close this ticket and open a new one.
