### ISSUE TITLE
Set breakpoint narrower for responsive survey

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#38]
The media breakpoint for turning the two column display into a single column display is too wide.  Not sure what it is now, but it could be set lower.  Perhaps 800px?  It should still have two columns until the page gets down to ipad mini size.   
![Screen Shot 2022-04-19 at 7 37 20 AM](https://user-images.githubusercontent.com/1187616/163995581-824b1b38-dcaf-44f8-98ae-d785be333634.png)
![Screen Shot 2022-04-19 at 7 37 44 AM](https://user-images.githubusercontent.com/1187616/163995591-78a8e0fc-1fdf-4e9d-889f-d6fe289c1112.png)

**Comment by aaronlugo** [comment]
done

**Comment by teveritt** [comment]
1200px is the smallest width that still displays both columns. Is this correct?

**Comment by teveritt** [comment]
Left column collapses at 800px width
