### ISSUE TITLE
Rearrange Start Survey page

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#40]
Make the following changes to the Start Survey Page:

1) Change "What is your system task" block to be checkboxes. Users must select at least one.  
2) Change the label "Which domain are you working in" to "Which domain is the application for?"
3) Make the domains radio buttons instead of checkboxes.  You must choose one domain for the survey. 
4) Put the samples in a responsive horizontal grid instead of vertical
5) Disable "Start Survey" button until at least one of each question is selected. 

<img width="1904" alt="Screen Shot 2022-04-19 at 9 47 13 AM" src="https://user-images.githubusercontent.com/1187616/164025291-2d34f83b-213c-4723-b697-14643ae48600.png">

<img width="1904" alt="Screen Shot 2022-04-19 at 9 47 13 AM copy" src="https://user-images.githubusercontent.com/1187616/164033068-84ef8c82-ecfd-4aa7-b483-51d387be7d16.png">

**Comment by aaronlugo** [comment]
Done

**Comment by teveritt** [comment]
This is unchanged for me
![Screenshot 2022-04-27 160341](https://user-images.githubusercontent.com/65302023/165622716-9ceb0c3c-8f0b-4796-bbdd-f879c029541f.png)

**Comment by aaronlugo** [comment]
<img width="1440" alt="Captura de Pantalla 2022-04-27 a la(s) 18 20 24" src="https://user-images.githubusercontent.com/24878290/165646885-9439c8d8-33bf-411e-81cb-e43763634aaa.png">

**Comment by aaronlugo** [comment]
@geverit4 Can you check the deploys

**Comment by teveritt** [comment]
Showing correctly on test.
