### ISSUE TITLE
Edit Existing Project should go to last location, not start over

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#42]
If you click on the Edit Action next to an in-process survey, the app should return to the last point in the survey.  

Don't show the starting page if a project is already in process. 

<img width="1437" alt="Screen Shot 2022-04-19 at 12 13 11 PM" src="https://user-images.githubusercontent.com/1187616/164048773-733acf91-060e-41da-8676-0fdfe4902fbc.png">

**Comment by aaronlugo** [comment]
This is Fix, @teveritt  Check with @geverit4  to check the deployed version
