### ISSUE TITLE
Type checking for Dimension ID

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#43]
It is not clear from the UI that the Dimension ID has to be an integer.  Add type checking to the UI and do not permit submission where the Dimension ID is not an integer.  Bonus if you make the default the highest unused Dimension ID in the database.  

`Object { _message: "Dimension validation failed", name: "ValidationError", message: "Dimension validation failed: dimensionID: Cast to Number failed for value \"TT\" (type string) at path \"dimensionID\"", … }`

**Comment by aaronlugo** [comment]
Done
