### ISSUE TITLE
Remove "Trusted Resources" tabs

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#44]
The Trusted AI Resources and Trusted AI Providers are no longer required.

**Comment by aaronlugo** [comment]
Done

**Comment by teveritt** [comment]
The tabs are still visible for me:
![Screenshot 2022-04-27 185608](https://user-images.githubusercontent.com/65302023/165644985-9abe5d7f-db5b-44bf-8667-a38c721a6026.png)

**Comment by aaronlugo** [comment]
@geverit4 I think the deploys are failing

**Comment by aaronlugo** [comment]
<img width="1440" alt="Captura de Pantalla 2022-04-27 a la(s) 18 19 31" src="https://user-images.githubusercontent.com/24878290/165646800-49756b88-1ba1-48ba-ba8d-384ca590969b.png">

**Comment by teveritt** [comment]
Confirmed removed on test
