### ISSUE TITLE
Make a Summary tab

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#48]
Create a "pseudo-dimension" called "Summary" that shows up as the leftmost tab, and make it look like the attached screen shot:

<img width="992" alt="Screen Shot 2022-05-25 at 1 52 47 PM" src="https://user-images.githubusercontent.com/1187616/170330534-fb496e61-7152-4b16-a764-15b471074b49.png">

**Comment by geverit4** [comment]
The current version is getting close.  @aaronlugo please add the "Benchmark" markers to the Dimensions tab.  The Benchmark value should be 50% of the Available points for that dimension.  Benchmarks are displayed for Subdimensions.

**Comment by aaronlugo** [comment]
This is done
