### ISSUE TITLE
Questions do not stay sorted in Survey Editor

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#51]
If you drag a question to another location in the list, it does auto-number, but it does not preserve the order,  so the dragged item returns to it's previous location when the page is refreshed.   We need to make the order sticky so that the underlying database preserves the order of questions as they are dragged around.

**Comment by aaronlugo** [comment]
Cannot Reproduce this

**Comment by geverit4** [comment]
Looks like this is just a problem that is not going to be solved.

**Comment by geverit4** [comment]
Closed.  Unresolved because of undiagnosed problem.
