### ISSUE TITLE
Re-order Dimension Tabs

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#55]
Re-order the Dimension tabs to be in the order described on the Figma screen shot.  

<img width="1155" alt="Screen Shot 2022-05-31 at 10 14 22 AM" src="https://user-images.githubusercontent.com/1187616/171194766-0424714b-bf81-49c0-9b30-2de670846af0.png">

<img width="1155" alt="Screen Shot 2022-05-31 at 9 43 33 AM" src="https://user-images.githubusercontent.com/1187616/171194547-d01430f9-35a5-4120-883c-1da4b59da838.png">

**Comment by aaronlugo** [comment]
done

**Comment by aaronlugo** [comment]
Report summary: we can remove, this is the download link (the idea was to be able to download ONLY the summary page, but maybe we get there later)
Full report: we can remove, this is the full report download link which is duplicated
Guide: this is the link to the guide (see Figma comment for the link), the "learn more" text besides questions also point to it
SO, my suggestion is to have 2 buttons up at the top of the page, one that says "Download report" and another that says "Assessment guide" (see Figma for details)
