### ISSUE TITLE
Project Names getting removed

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#63]
Identify issue with My Assessments -> System Name -> Project Names​.  They appear to be getting changed by some unknown process.  It appears to be working in Aaron's own instance.  We need to track down what is actually changing it from the real Project Name to an unknown name.  It appears to be in the System Details​ edit screen where the Project Name​ was changed to the Name of the AI System​.  As such, it might be that this process, when an update is done, it might be still updating the Project Name​ instead of the Name of the AI System​.  Aaron to try to make the change on his local system to see if he can replicate and then fix.

**Comment by aaronlugo** [comment]
This is fixed, only works with new projects @teveritt
