### ISSUE TITLE
Subtract "Earned" from "Available" to compute gray portion of stacked bar

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#69]
Subtract the "Earned" from the "Available" amount to get the size of the gray bar.  

For example, in the attached images, the "Human in the Loop/Autonomy" dimension should have a gray bar value of 51, which is 61 - 10.  If possible, the flyover callout should say

"Earned 10 out of 61 possible points"

<img width="1129" alt="Screen Shot 2022-06-27 at 8 29 24 PM" src="https://user-images.githubusercontent.com/1187616/176061770-809361a2-d49e-41b7-866c-37d593ae6ef9.png">
<img width="1129" alt="Screen Shot 2022-06-27 at 8 29 45 PM" src="https://user-images.githubusercontent.com/1187616/176061774-7740d86c-8cd1-475f-be87-198f5b55aab1.png">

**Comment by aaronlugo** [comment]
Done
