### ISSUE TITLE
Update subdimension report.

### ISSUE THREAD

**Issue by geverit4** [appliedrelevance/design-assistant#8]
Add support for subdimensions.  

- Create a table that looks like the attached screen shot.
- 
<img width="608" alt="Screen Shot 2022-03-10 at 10 28 48 AM" src="https://user-images.githubusercontent.com/1187616/157695271-f083912b-dd62-407d-b827-86340307505a.png">

- Add support for "description" field in the subdimensions collection schema so that we can display more than just the title. 

This will require changing the Mongoose schemas and possibly the API so that it supports the new description fields.

**Comment by aaronlugo** [comment]
Done
